/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElButtonGroup: (typeof import('element-plus/es'))['ElButtonGroup']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElInputNumber: (typeof import('element-plus/es'))['ElInputNumber']
    ElLink: (typeof import('element-plus/es'))['ElLink']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElUpload: (typeof import('element-plus/es'))['ElUpload']
    FileUpload: (typeof import('./src/components/FileUpload/FileUpload.vue'))['default']
    FileUploadDrawer: (typeof import('./src/components/FileUploadDrawer.vue'))['default']
    FormModal: (typeof import('./src/components/FormModal.vue'))['default']
  }
}
